spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ObjectOrientedSpotify
    username: root
    password: ${SQL_password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        globally_quoted_identifiers: true
        # Disable automatic table creation/update
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:schema.sql
